version: "3.3"

networks:
  database_cluster_cws:
    external: true

services:
  frontend-dev:
    container_name: frontend-react
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend/react-app:/app
    ports:
      - "8025:8025"
    restart: unless-stopped
    networks:
      - database_cluster_cws

  backend-dev:
    container_name: backend-laravel
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./backend/laravel-app:/var/www/html:delegated
    restart: unless-stopped
    networks:
      - database_cluster_cws

  web-server:
    container_name: webserver-nginx
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "8084:80"
    volumes:
      - ./backend/laravel-app:/var/www/html:delegated
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend-dev
    restart: unless-stopped
    networks:
      - database_cluster_cws

