version: "3.8"

networks:
  web-app:
    driver: bridge
    ipam: 
      driver: default
      config: 
          - subnet: 172.50.17.0/24

services:
  frontend-dev:
    container_name: frontend-react
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend/react-app:/app
    ports:
      - "8025:8025"
    networks:
       web-app:
          ipv4_address: "172.50.17.1"

  backend-dev:
    container_name: backend-laravel
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./backend/laravel-app:/var/www/html:delegated
    networks:
       web-app:
          ipv4_address: "172.50.17.2"
  web-server:
    container_name: webserver-nginx
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "8084:80"
    volumes:
      - ./backend/laravel-app:/var/www/html:delegated
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend-dev
      - redis
      - mysql_db
    networks:
       web-app:
          ipv4_address: "172.50.17.3"      

  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: web-app
    ports:
      - 3006:3006
    networks:
       web-app:
          ipv4_address: "172.50.17.4"
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1
    networks:
       web-app:
          ipv4_address: "172.50.17.5"
  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
       web-app:
          ipv4_address: "172.50.17.6"